package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenMarkdownCLIWritesCommandTree(t *testing.T) {
	mdOut := filepath.Join(t.TempDir(), "cli")
	if err := genMarkdownCLI(mdOut); err != nil {
		t.Fatalf("genMarkdownCLI: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(mdOut, "lzr.md"))
	if err != nil {
		t.Fatalf("reading lzr.md: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, "lzr") {
		t.Errorf("lzr.md does not mention the binary name")
	}
	if strings.Contains(s, "Auto generated by spf13/cobra") {
		t.Errorf("auto-gen tag present; markdown is not reproducible")
	}
	// A nested subcommand page must be generated.
	if _, err := os.Stat(filepath.Join(mdOut, "lzr_config_switch.md")); err != nil {
		t.Errorf("expected lzr_config_switch.md to be generated: %v", err)
	}
}

func TestWriteKeybindingsReference(t *testing.T) {
	path := filepath.Join(t.TempDir(), "keybindings.md")
	if err := writeKeybindings(path); err != nil {
		t.Fatalf("writeKeybindings: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	s := string(data)
	for _, want := range []string{
		"# Keybindings Reference",
		"## General & Navigation",
		"| Key | Action | Scope | Palette |",
		"command palette", // a known command Title
		"`editConfig`",    // a known keys.yaml field name
		"alias for `doctor`",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("keybindings.md missing %q", want)
		}
	}
}
