.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-pac - PAC file generation and serving


.SH SYNOPSIS
\fBlzr pac [flags]\fP


.SH DESCRIPTION
Generate or serve a PAC (Proxy Auto-Configuration) file so browsers can auto-select the lazyray proxy. Use the subcommands to print a PAC file or to serve it over HTTP.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for pac


.SH SEE ALSO
\fBlzr(1)\fP, \fBlzr-pac-generate(1)\fP, \fBlzr-pac-serve(1)\fP
