.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-service - Manage xray system service (autostart)


.SH SYNOPSIS
\fBlzr service [flags]\fP


.SH DESCRIPTION
Manage the user-scoped system service that starts xray-core automatically on login. Use 'lzr service install' to enable autostart, 'lzr service uninstall' to remove it, and 'lzr service status' to check it.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for service


.SH SEE ALSO
\fBlzr(1)\fP, \fBlzr-service-install(1)\fP, \fBlzr-service-status(1)\fP, \fBlzr-service-uninstall(1)\fP
