.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-config-restore - Restore configuration from a backup archive


.SH SYNOPSIS
\fBlzr config restore  [flags]\fP


.SH DESCRIPTION
Restore the profile store and the generated xray config from an archive made by 'lzr config backup'. Encrypted archives are detected automatically; the passphrase comes from --passphrase-file, the LAZYRAY_PASSPHRASE environment variable, or an interactive prompt. Plain tar.gz archives from older versions restore without a passphrase. Recognized members (servers.yaml, lazyray.yaml, config.json) overwrite the current files.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for restore

.PP
\fB--passphrase-file\fP=""
	Read the decryption passphrase from the first line of this file


.SH EXAMPLE
.EX
  lzr config restore ~/lazyray-backup.tar.gz.enc
  lzr config restore ./lazyray-backup-20260101-120000.tar.gz
.EE


.SH SEE ALSO
\fBlzr-config(1)\fP
