.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-config-restore - Restore configuration from tar.gz archive


.SH SYNOPSIS
\fBlzr config restore  [flags]\fP


.SH DESCRIPTION
Restore the profile store and the generated xray config from a tar.gz archive made by 'lzr config backup'. Recognized members (servers.yaml, lazyray.yaml, config.json) overwrite the current files. Use it to recover a setup or replicate it on another machine.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for restore


.SH EXAMPLE
.EX
  lzr config restore ~/lazyray-backup.tar.gz
  lzr config restore ./lazyray-backup-20260101-120000.tar.gz
.EE


.SH SEE ALSO
\fBlzr-config(1)\fP
