.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-service-status - Show service status


.SH SYNOPSIS
\fBlzr service status [flags]\fP


.SH DESCRIPTION
Report whether the user-scoped xray-core autostart service is installed and whether it is currently running. For full diagnostics of the running proxy use 'lzr doctor'.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH EXAMPLE
.EX
  lzr service status
.EE


.SH SEE ALSO
\fBlzr-service(1)\fP
