.nh
.TH "LZR" "1" "Jan 2026" "lazyray" "lazyray Manual"

.SH NAME
lzr-self-update - Update lazyray to the latest version


.SH SYNOPSIS
\fBlzr self-update [flags]\fP


.SH DESCRIPTION
Check for and install the latest version of lazyray from GitHub releases.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for self-update


.SH EXAMPLE
.EX
  lzr self-update
.EE


.SH SEE ALSO
\fBlzr(1)\fP
